application: trollhub
version: 1
runtime: python
api_version: 1

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?\..*
- chat_test

handlers:
- url: /static
  static_dir: static
  expiration: 1d

- url: .*
  script: main.py
  login: required

inbound_services:
- xmpp_message
- xmpp_presence
- xmpp_subscribe